// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using T_Car_Shop.Infrastructure;

#nullable disable

namespace T_Car_Shop.Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20240829172444_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("T_Car_Shop.Domain.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a44adc43-8d09-4f42-8a23-f646ca40b1ca"),
                            Name = "Tom"
                        },
                        new
                        {
                            Id = new Guid("39777c3b-5cff-4866-8f82-c8001a32b881"),
                            Name = "Bob"
                        },
                        new
                        {
                            Id = new Guid("e6a27170-2038-4518-a7db-3fd1fb176e8e"),
                            Name = "Sam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
